apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: petclinic/dev/terraform/database
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: petclinic/dev/terraform/database
        property: MYSQL_USER
    - secretKey: MYSQL_HOST
      remoteRef:
        key: petclinic/dev/terraform/database
        property: MYSQL_HOST
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: petclinic/dev/terraform/database
        property: MYSQL_DATABASE