apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-openai-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: openai-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_AI_OPENAI_API_KEY
      remoteRef:
        key: petclinic/dev/terraform/openai-api-key
        property: OPENAI_API_KEY